### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by Adrian-Swifter** [Adrian-Swifter/shoutout-lottery#3]
Check the render method of `TimeLeft`. See https://reactjs.org/link/warning-keys for more information.
    at span
    at TimeLeft (http://localhost:3000/static/js/bundle.js:661:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:190:92)

**Comment by Adrian-Swifter** [comment]
resolved by adding index as key in timeLeft
